package net.thevaliantsquidward.vintagevibes.registry;

import net.minecraft.data.BlockFamily;

import static net.thevaliantsquidward.vintagevibes.registry.VVBlocks.*;

public class VVBlockFamilies {
    public static final BlockFamily AMBER_TILES_FAMILY = new BlockFamily.Builder(AMBER_TILES.get()).slab(AMBER_TILE_SLAB.get()).stairs(AMBER_TILE_STAIRS.get()).wall(AMBER_TILE_WALL.get()).getFamily();
    public static final BlockFamily AQUAMARINE_TILES_FAMILY = new BlockFamily.Builder(AQUAMARINE_TILES.get()).slab(AQUAMARINE_TILE_SLAB.get()).stairs(AQUAMARINE_TILE_STAIRS.get()).wall(AQUAMARINE_TILE_WALL.get()).getFamily();
    public static final BlockFamily ENSTATITE_TILES_FAMILY = new BlockFamily.Builder(ENSTATITE_TILES.get()).slab(ENSTATITE_TILE_SLAB.get()).stairs(ENSTATITE_TILE_STAIRS.get()).wall(ENSTATITE_TILE_WALL.get()).getFamily();
    public static final BlockFamily GARNET_TILES_FAMILY = new BlockFamily.Builder(GARNET_TILES.get()).slab(GARNET_TILE_SLAB.get()).stairs(GARNET_TILE_STAIRS.get()).wall(GARNET_TILE_WALL.get()).getFamily();
    public static final BlockFamily JADE_TILES_FAMILY = new BlockFamily.Builder(JADE_TILES.get()).slab(JADE_TILE_SLAB.get()).stairs(JADE_TILE_STAIRS.get()).wall(JADE_TILE_WALL.get()).getFamily();
    public static final BlockFamily KUNZITE_TILES_FAMILY = new BlockFamily.Builder(KUNZITE_TILES.get()).slab(KUNZITE_TILE_SLAB.get()).stairs(KUNZITE_TILE_STAIRS.get()).wall(KUNZITE_TILE_WALL.get()).getFamily();
    public static final BlockFamily LARIMAR_TILES_FAMILY = new BlockFamily.Builder(LARIMAR_TILES.get()).slab(LARIMAR_TILE_SLAB.get()).stairs(LARIMAR_TILE_STAIRS.get()).wall(LARIMAR_TILE_WALL.get()).getFamily();
    public static final BlockFamily MILKY_QUARTZ_TILES_FAMILY = new BlockFamily.Builder(MILKY_QUARTZ_TILES.get()).slab(MILKY_QUARTZ_TILE_SLAB.get()).stairs(MILKY_QUARTZ_TILE_STAIRS.get()).wall(MILKY_QUARTZ_TILE_WALL.get()).getFamily();
    public static final BlockFamily MOONSTONE_TILES_FAMILY = new BlockFamily.Builder(MOONSTONE_TILES.get()).slab(MOONSTONE_TILE_SLAB.get()).stairs(MOONSTONE_TILE_STAIRS.get()).wall(MOONSTONE_TILE_WALL.get()).getFamily();
    public static final BlockFamily ONYX_TILES_FAMILY = new BlockFamily.Builder(ONYX_TILES.get()).slab(ONYX_TILE_SLAB.get()).stairs(ONYX_TILE_STAIRS.get()).wall(ONYX_TILE_WALL.get()).getFamily();
    public static final BlockFamily PERIDOT_TILES_FAMILY = new BlockFamily.Builder(PERIDOT_TILES.get()).slab(PERIDOT_TILE_SLAB.get()).stairs(PERIDOT_TILE_STAIRS.get()).wall(PERIDOT_TILE_WALL.get()).getFamily();
    public static final BlockFamily ROSE_QUARTZ_TILES_FAMILY = new BlockFamily.Builder(ROSE_QUARTZ_TILES.get()).slab(ROSE_QUARTZ_TILE_SLAB.get()).stairs(ROSE_QUARTZ_TILE_STAIRS.get()).wall(ROSE_QUARTZ_TILE_WALL.get()).getFamily();
    public static final BlockFamily SAPPHIRE_TILES_FAMILY = new BlockFamily.Builder(SAPPHIRE_TILES.get()).slab(SAPPHIRE_TILE_SLAB.get()).stairs(SAPPHIRE_TILE_STAIRS.get()).wall(SAPPHIRE_TILE_WALL.get()).getFamily();
    public static final BlockFamily SMOKY_QUARTZ_TILES_FAMILY = new BlockFamily.Builder(SMOKY_QUARTZ_TILES.get()).slab(SMOKY_QUARTZ_TILE_SLAB.get()).stairs(SMOKY_QUARTZ_TILE_STAIRS.get()).wall(SMOKY_QUARTZ_TILE_WALL.get()).getFamily();
    public static final BlockFamily TAAFFEITE_TILES_FAMILY = new BlockFamily.Builder(TAAFFEITE_TILES.get()).slab(TAAFFEITE_TILE_SLAB.get()).stairs(TAAFFEITE_TILE_STAIRS.get()).wall(TAAFFEITE_TILE_WALL.get()).getFamily();
    public static final BlockFamily TOPAZ_TILES_FAMILY = new BlockFamily.Builder(TOPAZ_TILES.get()).slab(TOPAZ_TILE_SLAB.get()).stairs(TOPAZ_TILE_STAIRS.get()).wall(TOPAZ_TILE_WALL.get()).getFamily();

    public static final BlockFamily AMETHYST_TILES_FAMILY = new BlockFamily.Builder(AMETHYST_TILES.get()).slab(AMETHYST_TILE_SLAB.get()).stairs(AMETHYST_TILE_STAIRS.get()).wall(AMETHYST_TILE_WALL.get()).getFamily();
    public static final BlockFamily DIAMOND_TILES_FAMILY = new BlockFamily.Builder(DIAMOND_TILES.get()).slab(DIAMOND_TILE_SLAB.get()).stairs(DIAMOND_TILE_STAIRS.get()).wall(DIAMOND_TILE_WALL.get()).getFamily();
    public static final BlockFamily EMERALD_TILES_FAMILY = new BlockFamily.Builder(EMERALD_TILES.get()).slab(EMERALD_TILE_SLAB.get()).stairs(EMERALD_TILE_STAIRS.get()).wall(EMERALD_TILE_WALL.get()).getFamily();
    public static final BlockFamily QUARTZ_TILES_FAMILY = new BlockFamily.Builder(QUARTZ_TILES.get()).slab(QUARTZ_TILE_SLAB.get()).stairs(QUARTZ_TILE_STAIRS.get()).wall(QUARTZ_TILE_WALL.get()).getFamily();

    public static final BlockFamily CALCITE_TILES_FAMILY = new BlockFamily.Builder(CALCITE_TILES.get()).slab(CALCITE_TILE_SLAB.get()).stairs(CALCITE_TILE_STAIRS.get()).wall(CALCITE_TILE_WALL.get()).getFamily();
    public static final BlockFamily CALCITE_BRICKS_FAMILY = new BlockFamily.Builder(CALCITE_BRICKS.get()).slab(CALCITE_BRICK_SLAB.get()).stairs(CALCITE_BRICK_STAIRS.get()).wall(CALCITE_BRICK_WALL.get()).getFamily();

    public static final BlockFamily AMBER_BEJEWELED_CALCITE_BRICKS_FAMILY = new BlockFamily.Builder(AMBER_BEJEWELED_CALCITE_BRICKS.get()).slab(AMBER_BEJEWELED_CALCITE_BRICK_SLAB.get()).stairs(AMBER_BEJEWELED_CALCITE_BRICK_STAIRS.get()).wall(AMBER_BEJEWELED_CALCITE_BRICK_WALL.get()).getFamily();
    public static final BlockFamily AQUAMARINE_BEJEWELED_CALCITE_BRICKS_FAMILY = new BlockFamily.Builder(AQUAMARINE_BEJEWELED_CALCITE_BRICKS.get()).slab(AQUAMARINE_BEJEWELED_CALCITE_BRICK_SLAB.get()).stairs(AQUAMARINE_BEJEWELED_CALCITE_BRICK_STAIRS.get()).wall(AQUAMARINE_BEJEWELED_CALCITE_BRICK_WALL.get()).getFamily();
    public static final BlockFamily ENSTATITE_BEJEWELED_CALCITE_BRICKS_FAMILY = new BlockFamily.Builder(ENSTATITE_BEJEWELED_CALCITE_BRICKS.get()).slab(ENSTATITE_BEJEWELED_CALCITE_BRICK_SLAB.get()).stairs(ENSTATITE_BEJEWELED_CALCITE_BRICK_STAIRS.get()).wall(ENSTATITE_BEJEWELED_CALCITE_BRICK_WALL.get()).getFamily();
    public static final BlockFamily GARNET_BEJEWELED_CALCITE_BRICKS_FAMILY = new BlockFamily.Builder(GARNET_BEJEWELED_CALCITE_BRICKS.get()).slab(GARNET_BEJEWELED_CALCITE_BRICK_SLAB.get()).stairs(GARNET_BEJEWELED_CALCITE_BRICK_STAIRS.get()).wall(GARNET_BEJEWELED_CALCITE_BRICK_WALL.get()).getFamily();
    public static final BlockFamily JADE_BEJEWELED_CALCITE_BRICKS_FAMILY = new BlockFamily.Builder(JADE_BEJEWELED_CALCITE_BRICKS.get()).slab(JADE_BEJEWELED_CALCITE_BRICK_SLAB.get()).stairs(JADE_BEJEWELED_CALCITE_BRICK_STAIRS.get()).wall(JADE_BEJEWELED_CALCITE_BRICK_WALL.get()).getFamily();
    public static final BlockFamily KUNZITE_BEJEWELED_CALCITE_BRICKS_FAMILY = new BlockFamily.Builder(KUNZITE_BEJEWELED_CALCITE_BRICKS.get()).slab(KUNZITE_BEJEWELED_CALCITE_BRICK_SLAB.get()).stairs(KUNZITE_BEJEWELED_CALCITE_BRICK_STAIRS.get()).wall(KUNZITE_BEJEWELED_CALCITE_BRICK_WALL.get()).getFamily();
    public static final BlockFamily LARIMAR_BEJEWELED_CALCITE_BRICKS_FAMILY = new BlockFamily.Builder(LARIMAR_BEJEWELED_CALCITE_BRICKS.get()).slab(LARIMAR_BEJEWELED_CALCITE_BRICK_SLAB.get()).stairs(LARIMAR_BEJEWELED_CALCITE_BRICK_STAIRS.get()).wall(LARIMAR_BEJEWELED_CALCITE_BRICK_WALL.get()).getFamily();
    public static final BlockFamily MILKY_QUARTZ_BEJEWELED_CALCITE_BRICKS_FAMILY = new BlockFamily.Builder(MILKY_QUARTZ_BEJEWELED_CALCITE_BRICKS.get()).slab(MILKY_QUARTZ_BEJEWELED_CALCITE_BRICK_SLAB.get()).stairs(MILKY_QUARTZ_BEJEWELED_CALCITE_BRICK_STAIRS.get()).wall(MILKY_QUARTZ_BEJEWELED_CALCITE_BRICK_WALL.get()).getFamily();
    public static final BlockFamily MOONSTONE_BEJEWELED_CALCITE_BRICKS_FAMILY = new BlockFamily.Builder(MOONSTONE_BEJEWELED_CALCITE_BRICKS.get()).slab(MOONSTONE_BEJEWELED_CALCITE_BRICK_SLAB.get()).stairs(MOONSTONE_BEJEWELED_CALCITE_BRICK_STAIRS.get()).wall(MOONSTONE_BEJEWELED_CALCITE_BRICK_WALL.get()).getFamily();
    public static final BlockFamily ONYX_BEJEWELED_CALCITE_BRICKS_FAMILY = new BlockFamily.Builder(ONYX_BEJEWELED_CALCITE_BRICKS.get()).slab(ONYX_BEJEWELED_CALCITE_BRICK_SLAB.get()).stairs(ONYX_BEJEWELED_CALCITE_BRICK_STAIRS.get()).wall(ONYX_BEJEWELED_CALCITE_BRICK_WALL.get()).getFamily();
    public static final BlockFamily PERIDOT_BEJEWELED_CALCITE_BRICKS_FAMILY = new BlockFamily.Builder(PERIDOT_BEJEWELED_CALCITE_BRICKS.get()).slab(PERIDOT_BEJEWELED_CALCITE_BRICK_SLAB.get()).stairs(PERIDOT_BEJEWELED_CALCITE_BRICK_STAIRS.get()).wall(PERIDOT_BEJEWELED_CALCITE_BRICK_WALL.get()).getFamily();
    public static final BlockFamily ROSE_QUARTZ_BEJEWELED_CALCITE_BRICKS_FAMILY = new BlockFamily.Builder(ROSE_QUARTZ_BEJEWELED_CALCITE_BRICKS.get()).slab(ROSE_QUARTZ_BEJEWELED_CALCITE_BRICK_SLAB.get()).stairs(ROSE_QUARTZ_BEJEWELED_CALCITE_BRICK_STAIRS.get()).wall(ROSE_QUARTZ_BEJEWELED_CALCITE_BRICK_WALL.get()).getFamily();
    public static final BlockFamily SAPPHIRE_BEJEWELED_CALCITE_BRICKS_FAMILY = new BlockFamily.Builder(SAPPHIRE_BEJEWELED_CALCITE_BRICKS.get()).slab(SAPPHIRE_BEJEWELED_CALCITE_BRICK_SLAB.get()).stairs(SAPPHIRE_BEJEWELED_CALCITE_BRICK_STAIRS.get()).wall(SAPPHIRE_BEJEWELED_CALCITE_BRICK_WALL.get()).getFamily();
    public static final BlockFamily SMOKY_QUARTZ_BEJEWELED_CALCITE_BRICKS_FAMILY = new BlockFamily.Builder(SMOKY_QUARTZ_BEJEWELED_CALCITE_BRICKS.get()).slab(SMOKY_QUARTZ_BEJEWELED_CALCITE_BRICK_SLAB.get()).stairs(SMOKY_QUARTZ_BEJEWELED_CALCITE_BRICK_STAIRS.get()).wall(SMOKY_QUARTZ_BEJEWELED_CALCITE_BRICK_WALL.get()).getFamily();
    public static final BlockFamily TAAFFEITE_BEJEWELED_CALCITE_BRICKS_FAMILY = new BlockFamily.Builder(TAAFFEITE_BEJEWELED_CALCITE_BRICKS.get()).slab(TAAFFEITE_BEJEWELED_CALCITE_BRICK_SLAB.get()).stairs(TAAFFEITE_BEJEWELED_CALCITE_BRICK_STAIRS.get()).wall(TAAFFEITE_BEJEWELED_CALCITE_BRICK_WALL.get()).getFamily();
    public static final BlockFamily TOPAZ_BEJEWELED_CALCITE_BRICKS_FAMILY = new BlockFamily.Builder(TOPAZ_BEJEWELED_CALCITE_BRICKS.get()).slab(TOPAZ_BEJEWELED_CALCITE_BRICK_SLAB.get()).stairs(TOPAZ_BEJEWELED_CALCITE_BRICK_STAIRS.get()).wall(TOPAZ_BEJEWELED_CALCITE_BRICK_WALL.get()).getFamily();

    public static final BlockFamily AMETHYST_BEJEWELED_CALCITE_BRICKS_FAMILY = new BlockFamily.Builder(AMETHYST_BEJEWELED_CALCITE_BRICKS.get()).slab(AMETHYST_BEJEWELED_CALCITE_BRICK_SLAB.get()).stairs(AMETHYST_BEJEWELED_CALCITE_BRICK_STAIRS.get()).wall(AMETHYST_BEJEWELED_CALCITE_BRICK_WALL.get()).getFamily();
    public static final BlockFamily DIAMOND_BEJEWELED_CALCITE_BRICKS_FAMILY = new BlockFamily.Builder(DIAMOND_BEJEWELED_CALCITE_BRICKS.get()).slab(DIAMOND_BEJEWELED_CALCITE_BRICK_SLAB.get()).stairs(DIAMOND_BEJEWELED_CALCITE_BRICK_STAIRS.get()).wall(DIAMOND_BEJEWELED_CALCITE_BRICK_WALL.get()).getFamily();
    public static final BlockFamily EMERALD_BEJEWELED_CALCITE_BRICKS_FAMILY = new BlockFamily.Builder(EMERALD_BEJEWELED_CALCITE_BRICKS.get()).slab(EMERALD_BEJEWELED_CALCITE_BRICK_SLAB.get()).stairs(EMERALD_BEJEWELED_CALCITE_BRICK_STAIRS.get()).wall(EMERALD_BEJEWELED_CALCITE_BRICK_WALL.get()).getFamily();
    public static final BlockFamily QUARTZ_BEJEWELED_CALCITE_BRICKS_FAMILY = new BlockFamily.Builder(QUARTZ_BEJEWELED_CALCITE_BRICKS.get()).slab(QUARTZ_BEJEWELED_CALCITE_BRICK_SLAB.get()).stairs(QUARTZ_BEJEWELED_CALCITE_BRICK_STAIRS.get()).wall(QUARTZ_BEJEWELED_CALCITE_BRICK_WALL.get()).getFamily();

}
