modLoader = "javafml"
loaderVersion = "[32,)"
license = "MIT"

[[mods]]
modId = "vintagevibes"
version = "${file.jarVersion}"
logoFile = "vintagevibes.png"
authors = "TheValiantSquidward, OmayPaty, platypushasnohat"
displayName = "Vintage Vibes"
description = '''Fun new decorations with a vintage and slight tropical theming!'''

[[dependencies.vintagevibes]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vintagevibes]]
modId = "forge"
mandatory = true
versionRange = "[47.1.3,)"
ordering = "AFTER"
side = "BOTH"